name: "AI-Powered Terraform QA"
description: "A GitHub Action to perform AI-powered quality assurance checks on Terraform configurations."
inputs:
  tf_apply_job:
    description: "The name of the job that ran 'terraform apply'."
    required: true
  gemini_api_key:
    description: "The API key for Gemini"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
