name: "Heimdall"
description: |
  The watchful guardian of cloud infrastructure:
  - AI-powered Terraform validation
  - Real-time security scanning
  - Deployment integrity checks
brand:
  icon: "shield"
  color: "blue-purple"

inputs:
  tf_apply_job_name:
    description: "Name of GitHub job that ran 'terraform apply'"
    required: true
    default: "apply"

  llm_provider:
    description: "AI service for test generation/execution"
    required: true
    default: "gemini"
    options:
      - "openai"
      - "anthropic"
      - "gemini"

  api_key:
    description: "API key for chosen AI provider"
    required: true
    sensitive: true

  failure_strategy:
    description: "Behavior when tests fail"
    required: false
    default: "rollback"
    options:
      - "rollback"
      - "alert-only"
      - "retry"

outputs:
  test_plan:
    description: "Generated test sequence in JSON format"
  execution_logs:
    description: "Raw output of test executions"
  exit_codes:
    description: "Map of test names to exit codes"
  infrastructure_status:
    description: "Final verdict (validated/needs_fixes)"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "${{ inputs.tf_apply_job }}"
    - "${{ inputs.llm_provider }}"
    - "${{ inputs.api_key }}"
    - "${{ inputs.failure_strategy }}"
